name: just_audio_background
description: An add-on for just_audio that supports background playback and media notifications.
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_background
version: 0.0.1-beta.5

dependencies:
  just_audio_platform_interface: ^4.1.0
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  audio_service: ^0.18.4
  audio_session: ^0.1.6+1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  rxdart: '>=0.26.0 <0.28.0'

dev_dependencies:
  flutter_lints: ^1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
